projects:
  PRJ:
    last_root: 42
    subtasks:
      '5': 3
      '12': 7
      12-2: 4
  TSK:
    last_root: 15
    subtasks: {}
  AL:
    last_root: 129
    subtasks:
      '115': 1
      '118': 8
      '128': 2
      '129': 2
